name: CI-CD Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and analyze with SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Build and push Docker image to Amazon ECR
        run: |
          # Replace with your Docker build and push commands
          CURRENT_DATE=$(date +%Y%m%d%H%M%S)
          IMAGE_TAG=654654157582.dkr.ecr.ap-south-1.amazonaws.com/docker-pipeline-2:$CURRENT_DATE
          
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 654654157582.dkr.ecr.ap-south-1.amazonaws.com
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
          
          # Tagging latest
          docker tag $IMAGE_TAG 654654157582.dkr.ecr.ap-south-1.amazonaws.com/docker-pipeline-2:latest
          docker push 654654157582.dkr.ecr.ap-south-1.amazonaws.com/docker-pipeline-2:latest
        env:
          ECR_REGISTRY: Private registry
          ECR_REPOSITORY: docker-pipeline-2
          AWS_REGION: ap-south-1
      - name: SSH into EC2 instance and pull Docker image
        uses: appleboy/ssh-action@master
        with:
          host: 13.232.119.224
          username: ubuntu  # Replace with your EC2 instance username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your SSH private key as a secret
          script: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 654654157582.dkr.ecr.ap-south-1.amazonaws.com
            docker pull 654654157582.dkr.ecr.ap-south-1.amazonaws.com/docker-pipeline-2:latest
            docker stop docker
            docker rm docker
            docker run -d -p 8085:8080 --name docker 654654157582.dkr.ecr.ap-south-1.amazonaws.com/docker-pipeline-2:latest    
